# My Portfolio

## Personal Information

Name: Lars Vervaele

<img src="foto.png" alt="Profile Picture" width="228" height="341">

### About Me
I am Lars Vervaele, a student of Applied Informatics at Hogeschool Gent. 
In my final year, I specialized in mainframe technology. 
I have a strong interest in software development, and my specialization has deepened my interest in the mainframe environment. 
I am a problem-solving thinker who loves new challenges.

### Curriculum Vitae

[CV](CV_LarsVervaele.pdf)

## Achievements

### Projects

- In the first year of my Applied Informatics course, I recreated the board game Zatre using Java and JavaFX.
- In the second year, we developed a web scraper in Python to fetch flight data from airline websites. We then used this data in PowerBI for analysis.

### Internship

During my internship at KBC Bank & Insurance in my final year, I was introduced to the software development cycle within the mainframe environment. 
I learned a lot and had the opportunity to write programs myself. 
Here, I gained knowledge in COBOL, PL/1, IMS, and JCL.

### Bachelor Thesis

- **Topic**: Integration of New COBOL Online Screens with Existing EGL (Auto-generated COBOL).

This thesis explores the integration of new COBOL online screens with existing COBOL screens generated by EGL. 
The motivation for this research is KBC's transition to a new version control tool, which limits support for EGL. 
Additionally, KBC aims to create a more uniform development environment due to the aging workforce and the need for smoother knowledge transfer.
The central research question is: How can native COBOL screens be integrated with existing EGL-generated COBOL screens? 
The goal of this research is to provide insight into the integration processes between EGL and COBOL screens and to describe practical steps for this integration.
The research was conducted by first performing an extensive study of the technologies used. 
Next, the functionality and communication methods of the screens were examined. 
Research was then conducted on possible techniques to integrate the native COBOL screens with the EGL screens. 
Finally, a Proof of Concept was developed.
The conclusion of this research shows that it is theoretically possible to integrate native COBOL with existing EGL screens, as evidenced by the literature review and the analysis of integration techniques. 
However, due to limitations in the KBC environment, which may be resolved in the future, the Proof of Concept could not be successfully implemented.

### Personal Achievements

- Earned IBM Mainframe Systems Operator Level I Certificate 2.5 (V2)
- Achieved IBM Z Xplore concepts, advanced, and extended badges

### Experiences

#### Current Technical Skills

Mainframe:
- COBOL, PL/1, IDz, JCL, EGL, IMS

Programming Languages:
- Java, JavaScript, NodeJS, C#, Python, SQL
